# Set all versions
CYANOGEN_BUILD_TYPE ?= UNOFFICIAL
CYANOGEN_VERSION_NUMBER :=1.0
CYANOGEN_DATE_YEAR := $(shell date -u +%Y)
CYANOGEN_DATE_MONTH := $(shell date -u +%m)
CYANOGEN_DATE_DAY := $(shell date -u +%d)
CYANOGEN_DATE_HOUR := $(shell date -u +%H)
CYANOGEN_DATE_MINUTE := $(shell date -u +%M)
CYANOGEN_BUILD_DATE_UTC := $(shell date -d '$(CYANOGEN_DATE_YEAR)-$(CYANOGEN_DATE_MONTH)-$(CYANOGEN_DATE_DAY) $(CYANOGEN_DATE_HOUR):$(CYANOGEN_DATE_MINUTE) UTC' +%s)
CYANOGEN_BUILD_DATE := $(CYANOGEN_DATE_YEAR)$(CYANOGEN_DATE_MONTH)$(CYANOGEN_DATE_DAY)-$(CYANOGEN_DATE_HOUR)$(CYANOGEN_DATE_MINUTE)

CYANOGEN_PLATFORM_VERSION := 10.0

TARGET_PRODUCT_SHORT := $(subst cyanogen_,,$(CYANOGEN_BUILD))

CYANOGEN_VERSION := CyanogenOS_$(CYANOGEN_BUILD)-$(CYANOGEN_PLATFORM_VERSION)-$(CYANOGEN_BUILD_DATE)-$(CYANOGEN_BUILD_TYPE)
CYANOGEN_VERSION_PROP := 10
ROM_FINGERPRINT := CyanogenOS/$(CYANOGEN_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CYANOGEN_BUILD_DATE)

CYANOGEN_PROPERTIES := \
    ro.cyanogen.version=$(CYANOGEN_VERSION_PROP) \
    ro.cyanogen.version.display=$(CYANOGEN_VERSION) \
    ro.cyanogen.build_date=$(CYANOGEN_BUILD_DATE) \
    ro.cyanogen.build_date_utc=$(CYANOGEN_BUILD_DATE_UTC) \
    ro.cyanogen.build_type=$(CYANOGEN_BUILD_TYPE) \
    ro.cyanogen.fingerprint=$(ROM_FINGERPRINT)

ifeq ($(CYANOGEN_BUILD_TYPE), OFFICIAL)
PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/secure/releasekey
endif
